<a href="https://colab.research.google.com/github/BrianXian20/Data-analysis/blob/main/Week_4_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Analysis Y3 -Week 4 Lab- Data Preprocessing

- In this lab you will be applying what we covered in our Tuesday’s class in pre-processing data including: Handling missing value.

- We'll be using a dataset for bulding permits in the US. You can downlaod the datset from the Moodel page.

**1. Import pandas and numpy, and read in the Buliding permits csv file and set it to a DataFrame called "permits".**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
permits = pd.read_csv("Building_Permits.csv")

<ipython-input-34-ed8d5e3fbdd6>:1: DtypeWarning: Columns (22,32) have mixed types. Specify dtype option on import or set low_memory=False.
  permits = pd.read_csv("Building_Permits.csv")

In [ ]:
permits.head()

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,2.02E+11,4,sign - erect,05/06/2015,326,23,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380000e+12
1,2.02E+11,4,sign - erect,04/19/2016,306,7,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420000e+12
2,2.02E+11,3,additions alterations or repairs,05/27/2016,595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.420000e+12
3,2.02E+11,8,otc alterations permit,11/07/2016,156,11,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.440000e+12
4,2.02E+11,6,demolitions,11/28/2016,342,1,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.450000e+11

**2. Check the head of the  first 10 rows in the DataFrame**

In [ ]:
permits.head(11)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,2.02E+11,4,sign - erect,05/06/2015,326,23,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380000e+12
1,2.02E+11,4,sign - erect,04/19/2016,306,7,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420000e+12
2,2.02E+11,3,additions alterations or repairs,05/27/2016,595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.420000e+12
3,2.02E+11,8,otc alterations permit,11/07/2016,156,11,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.440000e+12
4,2.02E+11,6,demolitions,11/28/2016,342,1,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.450000e+11
5,2.02E+11,8,otc alterations permit,06/14/2017,4105,9,800,NaN,Indiana,St,...,1.0,constr type 1,1.0,constr type 1,NaN,10.0,Potrero Hill,94107.0,"(37.75922331346539, -122.39170402628598)",1.470000e+12
6,2.02E+11,8,otc alterations permit,06/30/2017,1739,20,1291,NaN,11th,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,5.0,Inner Sunset,94122.0,"(37.764145640138565, -122.46875112470363)",1.470000e+12
7,M803667,8,otc alterations permit,06/30/2017,4789,14,1465,NaN,Revere,Av,...,NaN,NaN,NaN,NaN,NaN,10.0,Bayview Hunters Point,94124.0,"(37.73005099023611, -122.38784938916618)",1.470000e+12
8,M804227,8,otc alterations permit,07/05/2017,1212,54,2094,NaN,Fell,St,...,NaN,NaN,NaN,NaN,NaN,5.0,Lone Mountain/USF,94117.0,"(37.772393498502595, -122.45231466824669)",1.470000e+12
9,M804767,8,otc alterations permit,07/06/2017,1259,16,89,NaN,Alpine,Tr,...,NaN,NaN,NaN,NaN,NaN,8.0,Haight Ashbury,94117.0,"(37.7691724293766, -122.43734859051908)",1.470000e+11
10,M805287,8,otc alterations permit,07/06/2017,3541,1,106,NaN,Sanchez,St,...,NaN,NaN,NaN,NaN,NaN,8.0,Castro/Upper Market,94114.0,"(37.767349757757145, -122.43140682973024)",1.470000e+12

**3. Change the Datatype of the following columns into appropriate datatype:**
1.	Permit type
2.	Permit Creation Date
3.	Issued Date

In [ ]:
permits["Permit Type"] = permits["Permit Type"].astype('category')
print(permits.dtypes)

Permit Number                               object
Permit Type                               category
Permit Type Definition                      object
Permit Creation Date                      category
Block                                       object
Lot                                         object
Street Number                                int64
Street Number Suffix                        object
Street Name                                 object
Street Suffix                               object
Unit                                       float64
Unit Suffix                                 object
Description                                 object
Current Status                              object
Current Status Date                         object
Filed Date                                  object
Issued Date                                 object
Completed Date                              object
First Construction Document Date            object
Structural Notification                     object
Number of Existing Stories                 float64
Number of Proposed Stories                 float64
Voluntary Soft-Story Retrofit               object
Fire Only Permit                            object
Permit Expiration Date                      object
Estimated Cost                             float64
Revised Cost                               float64
Existing Use                                object
Existing Units                             float64
Proposed Use                                object
Proposed Units                             float64
Plansets                                   float64
TIDF Compliance                             object
Existing Construction Type                 float64
Existing Construction Type Description      object
Proposed Construction Type                 float64
Proposed Construction Type Description      object
Site Permit                                 object
Supervisor District                        float64
Neighborhoods - Analysis Boundaries         object
Zipcode                                    float64
Location                                    object
Record ID                                  float64
dtype: object

In [ ]:
permits["Permit Creation Date"] = pd.DataFrame
display(permits)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,2.02E+11,4,sign - erect,<class 'pandas.core.frame.DataFrame'>,326,23,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380000e+12
1,2.02E+11,4,sign - erect,<class 'pandas.core.frame.DataFrame'>,306,7,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420000e+12
2,2.02E+11,3,additions alterations or repairs,<class 'pandas.core.frame.DataFrame'>,595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.420000e+12
3,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,156,11,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.440000e+12
4,2.02E+11,6,demolitions,<class 'pandas.core.frame.DataFrame'>,342,1,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.450000e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109525,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,634,14,2584,NaN,California,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Pacific Heights,94115.0,"(37.78880861807629, -122.43684884572968)",1.440000e+11
109526,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,634,14,2586,NaN,California,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Pacific Heights,94115.0,"(37.78880861807629, -122.43684884572968)",1.440000e+12
109527,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,11,7,2800,NaN,Leavenworth,St,...,3.0,constr type 3,3.0,constr type 3,NaN,3.0,North Beach,94133.0,"(37.80738912319805, -122.41853873853351)",1.440000e+11
109528,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,78,72,383,NaN,Lombard,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,North Beach,94133.0,"(37.8032718153637, -122.40782558633313)",1.440000e+11
109529,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,5336,61,170,NaN,Bridgeview,Dr,...,5.0,wood frame (5),5.0,wood frame,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
permits["Issued Date"] =  pd.DataFrame
display(permits)

,Permit Number,Permit Type,Permit Type Definition,Permit Creation Date,Block,Lot,Street Number,Street Number Suffix,Street Name,Street Suffix,...,Existing Construction Type,Existing Construction Type Description,Proposed Construction Type,Proposed Construction Type Description,Site Permit,Supervisor District,Neighborhoods - Analysis Boundaries,Zipcode,Location,Record ID
0,2.02E+11,4,sign - erect,<class 'pandas.core.frame.DataFrame'>,326,23,140,NaN,Ellis,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.785719256680785, -122.40852313194863)",1.380000e+12
1,2.02E+11,4,sign - erect,<class 'pandas.core.frame.DataFrame'>,306,7,440,NaN,Geary,St,...,3.0,constr type 3,NaN,NaN,NaN,3.0,Tenderloin,94102.0,"(37.78733980600732, -122.41063199757738)",1.420000e+12
2,2.02E+11,3,additions alterations or repairs,<class 'pandas.core.frame.DataFrame'>,595,203,1647,NaN,Pacific,Av,...,1.0,constr type 1,1.0,constr type 1,NaN,3.0,Russian Hill,94109.0,"(37.7946573324287, -122.42232562979227)",1.420000e+12
3,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,156,11,1230,NaN,Pacific,Av,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,Nob Hill,94109.0,"(37.79595867909168, -122.41557405519474)",1.440000e+12
4,2.02E+11,6,demolitions,<class 'pandas.core.frame.DataFrame'>,342,1,950,NaN,Market,St,...,3.0,constr type 3,NaN,NaN,NaN,6.0,Tenderloin,94102.0,"(37.78315261897309, -122.40950883997789)",1.450000e+11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109525,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,634,14,2584,NaN,California,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Pacific Heights,94115.0,"(37.78880861807629, -122.43684884572968)",1.440000e+11
109526,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,634,14,2586,NaN,California,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,2.0,Pacific Heights,94115.0,"(37.78880861807629, -122.43684884572968)",1.440000e+12
109527,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,11,7,2800,NaN,Leavenworth,St,...,3.0,constr type 3,3.0,constr type 3,NaN,3.0,North Beach,94133.0,"(37.80738912319805, -122.41853873853351)",1.440000e+11
109528,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,78,72,383,NaN,Lombard,St,...,5.0,wood frame (5),5.0,wood frame (5),NaN,3.0,North Beach,94133.0,"(37.8032718153637, -122.40782558633313)",1.440000e+11
109529,2.02E+11,8,otc alterations permit,<class 'pandas.core.frame.DataFrame'>,5336,61,170,NaN,Bridgeview,Dr,...,5.0,wood frame (5),5.0,wood frame,NaN,NaN,NaN,NaN,NaN,NaN

**4.	How many total missing values in each colum**

In [ ]:
nan_count = permits.isna().sum()

print(nan_count)

Permit Number                                  0
Permit Type                                    0
Permit Type Definition                         0
Permit Creation Date                           0
Block                                          0
Lot                                            0
Street Number                                  0
Street Number Suffix                      108360
Street Name                                    0
Street Suffix                               1469
Unit                                       93811
Unit Suffix                               108434
Description                                  163
Current Status                                 0
Current Status Date                            0
Filed Date                                     0
Issued Date                                 5352
Completed Date                             47638
First Construction Document Date            5357
Structural Notification                   105923
Number of Existing Stories                 23078
Number of Proposed Stories                 23366
Voluntary Soft-Story Retrofit             109510
Fire Only Permit                           99431
Permit Expiration Date                     25238
Estimated Cost                             20474
Revised Cost                                2043
Existing Use                               22197
Existing Units                             27768
Proposed Use                               23068
Proposed Units                             27607
Plansets                                   20074
TIDF Compliance                           109529
Existing Construction Type                 23406
Existing Construction Type Description     23406
Proposed Construction Type                 23540
Proposed Construction Type Description     23540
Site Permit                               107061
Supervisor District                         1026
Neighborhoods - Analysis Boundaries         1028
Zipcode                                     1027
Location                                    1018
Record ID                                      1
dtype: int64

**5. Print out the percentage of the missing values in the dataset**

In [ ]:
#permits.isnull().sum() / data.shape[0] * 100
percent_missing = permits.isnull().sum() * 100 / len(permits)
print(percent_missing)

Permit Number                              0.000000
Permit Type                                0.000000
Permit Type Definition                     0.000000
Permit Creation Date                       0.000000
Block                                      0.000000
Lot                                        0.000000
Street Number                              0.000000
Street Number Suffix                      98.931800
Street Name                                0.000000
Street Suffix                              1.341185
Unit                                      85.648681
Unit Suffix                               98.999361
Description                                0.148818
Current Status                             0.000000
Current Status Date                        0.000000
Filed Date                                 0.000000
Issued Date                                4.886333
Completed Date                            43.493107
First Construction Document Date           4.890897
Structural Notification                   96.706838
Number of Existing Stories                21.070026
Number of Proposed Stories                21.332968
Voluntary Soft-Story Retrofit             99.981740
Fire Only Permit                          90.779695
Permit Expiration Date                    23.042089
Estimated Cost                            18.692596
Revised Cost                               1.865242
Existing Use                              20.265681
Existing Units                            25.351958
Proposed Use                              21.060897
Proposed Units                            25.204967
Plansets                                  18.327399
TIDF Compliance                           99.999087
Existing Construction Type                21.369488
Existing Construction Type Description    21.369488
Proposed Construction Type                21.491829
Proposed Construction Type Description    21.491829
Site Permit                               97.745823
Supervisor District                        0.936730
Neighborhoods - Analysis Boundaries        0.938556
Zipcode                                    0.937643
Location                                   0.929426
Record ID                                  0.000913
dtype: float64

**6.	How many missing values in the columns "Street Number Suffix" and "Zipcode" ?**

In [ ]:
street_number = permits['Street Number Suffix'].isna().sum()

print(street_number)

108360

In [ ]:
zip_code = permits["Zipcode"].isna().sum()

print(zip_code)

1027

**7.	Create new dataFrame named “pemits_dropped” that has all the column with empty values.**

In [ ]:
permits_dropped = permits.dropna(axis = 1)

**8.	Calculate all number of the dropped columns.**

In [ ]:
num_dropped_col = permits[1] - permits_dropped.shape[1]
print(num_dropped_col)

KeyError: ignored

**9.	Replacing all missing value in Street Number Suffix with “0”**

In [ ]:
permits["Street Number Suffix"].fillna(0, inplace = True)

**10.	what is the existing use of the units with the following permits No: M805907 and M839987**

In [ ]:
print(permits("permit number")) == "M805907"

TypeError: ignored

In [ ]:
print(permits("permit number")) == "M839987"

TypeError: ignored